### ISSUE TITLE
undefined method in index.js:417

### ISSUE THREAD

**Issue by krebsBenjamin** [squarebracket/karma-selenium-grid-launcher#4]
When stopping a session the following error message is produced: 

ReferenceError: resolve is not defined
    at _stopSession.then (node_modules/karma-selenium-grid-launcher/index.js:417:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

There are already a pull request available fixing this issue. Can you merge that and produce a new release?

Much appreciated.
/Benjamin

**Comment by gogza** [comment]
This is the same issue as [Issue 5](https://github.com/squarebracket/karma-selenium-grid-launcher/issues/5) - if you are looking for a working copy - go see [ErDmKo's fork](https://github.com/ErDmKo/karma-selenium-grid-launcher).
