### ISSUE TITLE
UnhandledRejection error at end of test

### ISSUE THREAD

**Issue by nzeroplus** [squarebracket/karma-selenium-grid-launcher#5]
[2020-07-09T00:48:41.142Z] 09 07 2020 00:48:40.828:INFO [SeleniumGrid]: Killed grid_selenium_chrome.

[2020-07-09T00:48:41.142Z] 09 07 2020 00:48:40.830:ERROR [karma-server]: UnhandledRejection: resolve is not defined

[2020-07-09T00:48:41.142Z] 09 07 2020 00:48:40.831:ERROR [karma-server]: [ReferenceError: resolve is not defined

[2020-07-09T00:48:41.142Z]   at /home/jenkins/agent/workspace/pipeline_PR-195/node_modules/karma-selenium-grid-launcher/index.js:417:11

[2020-07-09T00:48:41.142Z]   at runMicrotasks (<anonymous>:null:null)

[2020-07-09T00:48:41.142Z]   at processTicksAndRejections (internal/process/task_queues.js:97:5)

[2020-07-09T00:48:41.142Z] ]

[2020-07-09T00:48:41.142Z] Warning: Task "karma:unit" failed. Use --force to continue.

**Comment by gogza** [comment]
Would be nice to get this fixed - always looks like the tests are failing. I might have a look.
